---
permalink: task-download-the-open-virtual-appliance.html 
sidebar: sidebar 
keywords: download, open virtual appliance 
summary: 'Téléchargez l"appliance virtuelle ouverte (OVA) dans VMware vCenter 8.0 et versions ultérieures pour déployer la sauvegarde et la restauration BlueXP pour les machines virtuelles.' 
---
= Téléchargez Open Virtual Appliance
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Téléchargez l'appliance virtuelle ouverte (OVA) dans VMware vCenter 8.0 et versions ultérieures pour déployer la sauvegarde et la restauration BlueXP pour les machines virtuelles.

.Avant de commencer
Si l'OVA signée par le certificat Entrust n'est pas fiable, assurez-vous d'installer et d'ajouter des certificats intermédiaires à vCenter.

.Étapes
. Pour télécharger la sauvegarde et la restauration BlueXP pour les VM OVA :
+
.. Connectez-vous au https://mysupport.netapp.com/products/index.html["Site de support NetApp"^]
.. Dans la liste de produits, sélectionnez *BlueXP Backup and Recovery for VMs*, puis cliquez sur le bouton *Télécharger la dernière version*.
.. Téléchargez la sauvegarde et la restauration BlueXP pour les VM `.tar` fichier à n'importe quel emplacement.


. Extraire le contenu du fichier tar. Le fichier tar contient le dossier OVA et certs. Le dossier certificats contient des certificats intermédiaires.
. Dans le client vSphere, accédez à *Administration > certificats > gestion des certificats*.
. En regard de *certificats racine de confiance*, cliquez sur *Ajouter*.
+

NOTE: Par défaut, le certificat racine est installé.

+
.. Accédez au dossier certs.
.. Sélectionnez les certificats intermédiaires.
.. Installez chaque certificat un par un.


. Les certificats sont ajoutés à un panneau sous certificats racine approuvés.
+
Une fois les certificats installés, une OVA peut être vérifiée et déployée.



[NOTE]
====
Si l'OVA téléchargée n'est pas falsifiée, la colonne Éditeur affiche certificat approuvé.

====