---
permalink: whats-new.html 
sidebar: sidebar 
keywords: 2-node switched Cisco 92300YC cluster switch migration 
summary: Découvrez les nouveautés de BlueXP pour la sauvegarde et la restauration des machines virtuelles. 
---
= Nouveautés de la sauvegarde et de la restauration BlueXP pour les machines virtuelles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouveautés de BlueXP pour la sauvegarde et la restauration des machines virtuelles.



== 18 janvier 2024



=== Améliorations apportées à la sauvegarde et à la restauration BlueXP pour les machines virtuelles

Les fonctionnalités suivantes sont prises en charge par la sauvegarde et la restauration BlueXP pour les machines virtuelles 1.1 :

* Monter et démonter les datastores
* Attacher et détacher les VMDK
* Restaurez des machines virtuelles à un autre emplacement
* Activez le verrouillage des snapshots pour vous assurer que les copies Snapshot ne sont pas falsifiées avant une heure spécifiée.




== 13 juillet 2023



=== La sauvegarde et la restauration BlueXP pour les machines virtuelles 1.0 sont désormais disponibles dans la version GA

Vous pouvez protéger les données de vos machines virtuelles à l'aide de la sauvegarde et de la restauration BlueXP pour les machines virtuelles. Vous pouvez sauvegarder des datastores sur Amazon FSX et restaurer les machines virtuelles à leur emplacement d'origine.

Cette solution est spécifiquement destinée aux machines virtuelles et aux datastores sur VMware Cloud on AWS et Amazon FSX for NetApp ONTAP.

link:concept-bluexp-backup-and-recovery-for-virtual-machines-on-amazon-fsx.html["Sauvegarde et restauration BlueXP pour les machines virtuelles sur Amazon FSX"]
